image: docker.io/cheeza42/dockerizing-project:20251112-094003
image: docker.io/cheeza42/dockerizing-project:20251112-094003
  repository: docker.io/cheeza42/dockerizing-project
  tag: ""

deployment:
  enabled: true
  replicaset: 2

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetport: 5001

ingress:
  enabled: true
  ingressClassName: nginx

aws:
  accessKeyId: AWS_ACCESS_KEY_ID
  secretAccessKey: AWS_SECRET_ACCESS_KEY
  region: us-east-1
