apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . | default .Release.Name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaset }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.name" . | default .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app.name" . | default .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "app.name" . | default .Release.Name }}
          image: {{ .Values.deployment.imagename }}{{- if .Values.deployment.imagetag }}:{{ .Values.deployment.imagetag }}{{- end }}
          ports:
            - containerPort: {{ .Values.service.targetport }}
