apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  {{- $ing := .Values.ingress | default (dict) }}
  {{- if (default false $ing.enabled) }}
  type: ClusterIP
  {{- else }}
  type: LoadBalancer
  {{- end }}
  selector:
    app: {{ .Release.Name }}
  {{- $svc := .Values.service | default (dict) }}
  ports:
    - port: {{ $svc.port | default 80 }}
      targetPort: {{ $svc.targetPort | default 80 }}
      protocol: TCP
      name: http

